// Code generated by goplus from parser.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package participle provides grammar-indexed parser construction with
// immutable spans, explicit commit semantics, and typed AST output.
package participle

// Span[n] covers exactly n grammar tokens. Offsets are byte offsets and the
// end is exclusive.
//
//goplus:enum Span[n nat]
//goplus:derive off
type Span interface{ isSpan() }

//goplus:variant (Span) spanValue(Start int, End int, Tokens int) Span[n]
type spanValue struct {
	start  int
	end    int
	tokens int
}

func (spanValue) isSpan() {}

type Assignment struct {
	Name  string
	Value int64
	Span  Span
}

// Expression[n] is a grammar AST indexed by its minimum token consumption.
// Lookahead consumes zero, commit preserves consumption, alternatives must
// agree, sequence adds, and repetition has a zero-token lower bound.
//
//goplus:enum Expression[n nat]
type Expression interface{ isExpression() }

//goplus:variant (Expression) Empty() Expression[0]
type Empty struct{}

func (Empty) isExpression() {}

//goplus:variant (Expression) Token(Symbol string) Expression[1]
type Token struct {
	Symbol string
}

func (Token) isExpression() {}

//goplus:variant (Expression) Sequence(Prefix Expression[n], Last Expression[1]) Expression[n+1]
type Sequence struct {
	Prefix Expression
	Last   Expression
}

func (Sequence) isExpression() {}

//goplus:variant (Expression) Alternative(Left Expression[n], Right Expression[n]) Expression[n]
type Alternative struct {
	Left  Expression
	Right Expression
}

func (Alternative) isExpression() {}

//goplus:variant (Expression) Lookahead(Body Expression[n]) Expression[0]
type Lookahead struct {
	Body Expression
}

func (Lookahead) isExpression() {}

//goplus:variant (Expression) Guarded(Guard Expression[0], Body Expression[n]) Expression[n]
type Guarded struct {
	Guard Expression
	Body  Expression
}

func (Guarded) isExpression() {}

//goplus:variant (Expression) Commit(Body Expression[n]) Expression[n]
type Commit struct {
	Body Expression
}

func (Commit) isExpression() {}

//goplus:variant (Expression) Many(Body Expression[n]) Expression[0]
type Many struct {
	Body Expression
}

func (Many) isExpression() {}

// ExpressionCases selects one handler per Expression variant for ExpressionFold.
type ExpressionCases[R any] struct {
	Empty       func() R
	Token       func(Symbol string) R
	Sequence    func(Prefix Expression, Last Expression) R
	Alternative func(Left Expression, Right Expression) R
	Lookahead   func(Body Expression) R
	Guarded     func(Guard Expression, Body Expression) R
	Commit      func(Body Expression) R
	Many        func(Body Expression) R
}

// ExpressionFold reduces Expression by one-level case analysis.
func ExpressionFold[R any](e Expression, cs ExpressionCases[R]) R {
	switch m := any(e).(type) {
	case Empty:
		return cs.Empty()
	case Token:
		return cs.Token(m.Symbol)
	case Sequence:
		return cs.Sequence(m.Prefix, m.Last)
	case Alternative:
		return cs.Alternative(m.Left, m.Right)
	case Lookahead:
		return cs.Lookahead(m.Body)
	case Guarded:
		return cs.Guarded(m.Guard, m.Body)
	case Commit:
		return cs.Commit(m.Body)
	case Many:
		return cs.Many(m.Body)
	default:
		panic("goplus: impossible enum value in ExpressionFold")
	}
}

// Grammar[g] is an immutable grammar identity and its FIRST set.
//
//goplus:enum Grammar[g nat]
//goplus:derive off
type Grammar interface{ isGrammar() }

//goplus:variant (Grammar) grammarValue(ID int, Name string, Root Expression[0], First []string) Grammar[g]
type grammarValue struct {
	iD    int
	name  string
	root  Expression
	first []string
}

func (grammarValue) isGrammar() {}

// SomeGrammar is the dynamic-loading boundary. It hides the static grammar
// identity until BindAssignments checks and reintroduces a requested witness.
//
//goplus:enum SomeGrammar
type SomeGrammar interface{ isSomeGrammar() }

//goplus:variant (SomeGrammar) LoadedAssignments(ID int, Root Expression[0], First []string)
type LoadedAssignments struct {
	ID    int
	Root  Expression
	First []string
}

func (LoadedAssignments) isSomeGrammar() {}

// SomeGrammarCases selects one handler per SomeGrammar variant for SomeGrammarFold.
type SomeGrammarCases[R any] struct {
	LoadedAssignments func(ID int, Root Expression, First []string) R
}

// SomeGrammarFold reduces SomeGrammar by one-level case analysis.
func SomeGrammarFold[R any](s SomeGrammar, cs SomeGrammarCases[R]) R {
	switch m := any(s).(type) {
	case LoadedAssignments:
		return cs.LoadedAssignments(m.ID, m.Root, m.First)
	default:
		panic("goplus: impossible enum value in SomeGrammarFold")
	}
}

// FirstSet[g] is evidence computed for exactly Grammar[g].
//
//goplus:enum FirstSet[g nat]
//goplus:derive off
type FirstSet interface{ isFirstSet() }

//goplus:variant (FirstSet) firstSetValue(GrammarID int, Symbols []string) FirstSet[g]
type firstSetValue struct {
	grammarID int
	symbols   []string
}

func (firstSetValue) isFirstSet() {}

// Parser[g,T] can only produce T for Grammar[g].
type parserRunner[T any] func(string) (T, *Failure)

//goplus:enum Parser[g nat, T any]
//goplus:derive off
type Parser[T any] interface{ isParser(T) }

//goplus:variant (Parser[T]) parserValue(GrammarID int, Run parserRunner[T]) Parser[g, T]
type parserValue[T any] struct {
	grammarID int
	run       parserRunner[T]
}

func (parserValue[T]) isParser(T) {}

//goplus:variant (Parser[T]) parserInvalid(Failure Failure) Parser[g, T]
type parserInvalid[T any] struct {
	failure Failure
}

func (parserInvalid[T]) isParser(T) {}

//goplus:enum FailureKind
type FailureKind interface{ isFailureKind() }

//goplus:variant (FailureKind) UnexpectedByte
type UnexpectedByte struct{}

func (UnexpectedByte) isFailureKind() {}

//goplus:variant (FailureKind) ExpectedIdentifier
type ExpectedIdentifier struct{}

func (ExpectedIdentifier) isFailureKind() {}

//goplus:variant (FailureKind) ExpectedEquals
type ExpectedEquals struct{}

func (ExpectedEquals) isFailureKind() {}

//goplus:variant (FailureKind) ExpectedInteger
type ExpectedInteger struct{}

func (ExpectedInteger) isFailureKind() {}

//goplus:variant (FailureKind) IntegerOverflow
type IntegerOverflow struct{}

func (IntegerOverflow) isFailureKind() {}

//goplus:variant (FailureKind) AmbiguousFirstSet
type AmbiguousFirstSet struct{}

func (AmbiguousFirstSet) isFailureKind() {}

// FailureKindCases selects one handler per FailureKind variant for FailureKindFold.
type FailureKindCases[R any] struct {
	UnexpectedByte     func() R
	ExpectedIdentifier func() R
	ExpectedEquals     func() R
	ExpectedInteger    func() R
	IntegerOverflow    func() R
	AmbiguousFirstSet  func() R
}

// FailureKindFold reduces FailureKind by one-level case analysis.
func FailureKindFold[R any](f FailureKind, cs FailureKindCases[R]) R {
	switch any(f).(type) {
	case UnexpectedByte:
		return cs.UnexpectedByte()
	case ExpectedIdentifier:
		return cs.ExpectedIdentifier()
	case ExpectedEquals:
		return cs.ExpectedEquals()
	case ExpectedInteger:
		return cs.ExpectedInteger()
	case IntegerOverflow:
		return cs.IntegerOverflow()
	case AmbiguousFirstSet:
		return cs.AmbiguousFirstSet()
	default:
		panic("goplus: impossible enum value in FailureKindFold")
	}
}

// FailureKindEqOverrides carries optional per-variant hooks for FailureKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureKindEqOverrides struct {
	UnexpectedByte     func(x, y UnexpectedByte) (eq, handled bool)
	ExpectedIdentifier func(x, y ExpectedIdentifier) (eq, handled bool)
	ExpectedEquals     func(x, y ExpectedEquals) (eq, handled bool)
	ExpectedInteger    func(x, y ExpectedInteger) (eq, handled bool)
	IntegerOverflow    func(x, y IntegerOverflow) (eq, handled bool)
	AmbiguousFirstSet  func(x, y AmbiguousFirstSet) (eq, handled bool)
}

// FailureKindEqualWith reports structural equality of a and b under ov.
func FailureKindEqualWith(a, b FailureKind, ov FailureKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case UnexpectedByte:
		y, ok := any(b).(UnexpectedByte)
		if !ok {
			return false
		}
		if ov.UnexpectedByte != nil {
			if eq, handled := ov.UnexpectedByte(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExpectedIdentifier:
		y, ok := any(b).(ExpectedIdentifier)
		if !ok {
			return false
		}
		if ov.ExpectedIdentifier != nil {
			if eq, handled := ov.ExpectedIdentifier(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExpectedEquals:
		y, ok := any(b).(ExpectedEquals)
		if !ok {
			return false
		}
		if ov.ExpectedEquals != nil {
			if eq, handled := ov.ExpectedEquals(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExpectedInteger:
		y, ok := any(b).(ExpectedInteger)
		if !ok {
			return false
		}
		if ov.ExpectedInteger != nil {
			if eq, handled := ov.ExpectedInteger(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case IntegerOverflow:
		y, ok := any(b).(IntegerOverflow)
		if !ok {
			return false
		}
		if ov.IntegerOverflow != nil {
			if eq, handled := ov.IntegerOverflow(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AmbiguousFirstSet:
		y, ok := any(b).(AmbiguousFirstSet)
		if !ok {
			return false
		}
		if ov.AmbiguousFirstSet != nil {
			if eq, handled := ov.AmbiguousFirstSet(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FailureKindEqual reports structural equality of a and b.
func FailureKindEqual(a, b FailureKind) bool {
	return FailureKindEqualWith(a, b, FailureKindEqOverrides{})
}

type Failure struct {
	Kind       FailureKind
	Offset     int
	Line       int
	Column     int
	Unexpected string
	Expected   []string
}

func (failure Failure) Error() string { return failureMessage(failure) }

//goplus:enum Outcome[T any]
type Outcome[T any] interface{ isOutcome(T) }

//goplus:variant (Outcome[T]) Parsed(Value T)
type Parsed[T any] struct {
	Value T
}

func (Parsed[T]) isOutcome(T) {}

//goplus:variant (Outcome[T]) Rejected(Failure Failure)
type Rejected[T any] struct {
	Failure Failure
}

func (Rejected[T]) isOutcome(T) {}

// OutcomeCases selects one handler per Outcome variant for OutcomeFold.
type OutcomeCases[T any, R any] struct {
	Parsed   func(Value T) R
	Rejected func(Failure Failure) R
}

// OutcomeFold reduces Outcome[T] by one-level case analysis.
func OutcomeFold[T any, R any](o Outcome[T], cs OutcomeCases[T, R]) R {
	switch m := any(o).(type) {
	case Parsed[T]:
		return cs.Parsed(m.Value)
	case Rejected[T]:
		return cs.Rejected(m.Failure)
	default:
		panic("goplus: impossible enum value in OutcomeFold")
	}
}

// AssignmentGrammar is: (Identifier '=' Integer Separator*)* EOF.
//
//goplus:dep AssignmentGrammar(id nat) Grammar[id]
func AssignmentGrammar(id int) Grammar {
	assignment := Sequence{Prefix: Sequence{Prefix: Token{Symbol: "Identifier"}, Last: Token{Symbol: "="}}, Last: Token{Symbol: "Integer"}}
	root := Many{Body: Guarded{Guard: Lookahead{Body: Token{Symbol: "Identifier"}}, Body: Commit{Body: assignment}}}
	return grammarValue{iD: int(id), name: "assignments", root: root, first: []string{"Identifier", "EOF"}}
}

//goplus:dep AssignmentFirst(0 id nat, grammar Grammar[id]) FirstSet[id]
func AssignmentFirst(grammar Grammar) FirstSet {
	switch __gp_m0 := any(grammar).(type) {
	case grammarValue:
		grammarID := __gp_m0.iD
		first := __gp_m0.first
		return firstSetValue{grammarID: grammarID, symbols: append([]string(nil), first...)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// AssignmentFirstFor is the explicit witness constructor used when grammar
// and FIRST evidence are loaded independently across a package boundary.
//
//goplus:dep AssignmentFirstFor(id nat) FirstSet[id]
func AssignmentFirstFor(id int) FirstSet {
	return firstSetValue{grammarID: int(id), symbols: []string{"Identifier", "EOF"}}
}

func LoadAssignments(id int) SomeGrammar {
	assignment := Sequence{Prefix: Sequence{Prefix: Token{Symbol: "Identifier"}, Last: Token{Symbol: "="}}, Last: Token{Symbol: "Integer"}}
	return LoadedAssignments{ID: id, Root: Many{Body: Guarded{Guard: Lookahead{Body: Token{Symbol: "Identifier"}}, Body: Commit{Body: assignment}}}, First: []string{"Identifier", "EOF"}}
}

//goplus:dep BindAssignments(id nat, loaded SomeGrammar) Grammar[id]
func BindAssignments(id int, loaded SomeGrammar) Grammar {
	switch __gp_m1 := any(loaded).(type) {
	case LoadedAssignments:
		loadedID := __gp_m1.ID
		root := __gp_m1.Root
		first := __gp_m1.First

		if loadedID != int(id) {
			panic("participle: dynamic grammar identity mismatch")
		}
		return grammarValue{iD: loadedID, name: "assignments", root: root, first: append([]string(nil), first...)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NewSpan(tokens nat, start int, end int) Span[tokens]
func NewSpan(tokens int, start int, end int) Span {
	if tokens < 0 || start < 0 || end < start {
		panic("participle: invalid span")
	}
	return spanValue{start: start, end: end, tokens: int(tokens)}
}

//goplus:dep SpanStart(0 n nat, span Span[n]) int
func SpanStart(span Span) int {
	switch __gp_m2 := any(span).(type) {
	case spanValue:
		start := __gp_m2.start
		return start
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep SpanEnd(0 n nat, span Span[n]) int
func SpanEnd(span Span) int {
	switch __gp_m3 := any(span).(type) {
	case spanValue:
		end := __gp_m3.end
		return end
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BuildAssignments(0 g nat, grammar Grammar[g], first FirstSet[g]) Parser[g, []Assignment]
func BuildAssignments(grammar Grammar, first FirstSet) Parser[[]Assignment] {
	failure := validateFirst(grammar, first)
	if failure != nil {
		return parserInvalid[[]Assignment]{failure: *failure}
	}
	switch __gp_m4 := any(grammar).(type) {
	case grammarValue:
		grammarID := __gp_m4.iD
		return parserValue[[]Assignment]{grammarID: grammarID, run: parseAssignments}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep validateFirst(0 g nat, grammar Grammar[g], first FirstSet[g]) *Failure
func validateFirst(grammar Grammar, first FirstSet) *Failure {
	switch __gp_m5 := any(grammar).(type) {
	case grammarValue:
		grammarID := __gp_m5.iD

		switch __gp_m6 := any(first).(type) {
		case firstSetValue:
			evidenceID := __gp_m6.grammarID
			symbols := __gp_m6.symbols

			if grammarID != evidenceID {
				panic("participle: FIRST evidence belongs to another grammar")
			}
			if hasDuplicate(symbols) {
				return &Failure{Kind: AmbiguousFirstSet{}, Expected: append([]string(nil), symbols...)}
			}
			return nil
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Parse[T any](0 g nat, parser Parser[g, T], input string) Outcome[T]
func Parse[T any](parser Parser[T], input string) Outcome[T] {
	switch __gp_m7 := any(parser).(type) {
	case parserValue[T]:
		run := __gp_m7.run

		value, failure := run(input)
		if failure != nil {
			return Rejected[T]{Failure: *failure}
		}
		return Parsed[T]{Value: value}
	case parserInvalid[T]:
		failure := __gp_m7.failure
		return Rejected[T]{Failure: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func hasDuplicate(symbols []string) bool {
	seen := make(map[string]bool, len(symbols))
	for _, symbol := range symbols {
		if seen[symbol] {
			return true
		}
		seen[symbol] = true
	}
	return false
}
