// Code generated by goplus from parser_java_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

//go:build goplus_java

package participle

import "testing"

func TestJavaAssignments(t *testing.T) {
	grammar := AssignmentGrammar(17)
	parser := BuildAssignments(grammar, AssignmentFirst(grammar))
	switch __gp_m0 := any(Parse[[]Assignment](parser, "workers=3; sprintDays=10")).(type) {
	case nil:
		//goplus:pattern Rejected(failure)
		t.Fatal(failure.Error())
	case nil:
		//goplus:pattern Parsed(values)

		if len(values) != 2 {
			t.Fatal("want two assignments")
		}
		if values[0].Name != "workers" || values[0].Value != 3 {
			t.Fatal("wrong first assignment")
		}
		if values[1].Name != "sprintDays" || values[1].Value != 10 {
			t.Fatal("wrong second assignment")
		}
	}
}

func TestJavaFailurePosition(t *testing.T) {
	grammar := AssignmentGrammar(18)
	parser := BuildAssignments(grammar, AssignmentFirst(grammar))
	switch __gp_m1 := any(Parse[[]Assignment](parser, "workers=no")).(type) {
	case nil:
		//goplus:pattern Parsed(_)
		t.Fatal("invalid integer parsed")
	case nil:
		//goplus:pattern Rejected(failure)

		if failure.Line != 1 || failure.Column != 9 {
			t.Fatal("wrong failure position")
		}
	}
}
